name: test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ert:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version: ['27.2', '28.2', '29.4']
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: Byte-compile
        run: make compile
      - name: Run ERT suite
        run: make test
